baseURL = "http://example.org/"
languageCode = "es-mx"
title = "Gophers LATAM"
theme = "basic"
[params]
    author = "ZeroIdentidad"
    description = "Gophers LATAM site"

gh_url = "https://api.github.com/users"
gh_user = "gophers-latam"